baseURL = 'https://keswick-rt.co.uk/'
languageCode = 'en-gb'
title = 'Keswick Round Table'
theme = "hugo-split-gallery"
copyright = "© 2025 Keswick Round Table. All rights reserved."

[params]
  [params.socialIcons]
    facebook = "https://www.facebook.com/rtkeswick"
    instagram = "https://www.instagram.com/keswick_roundtable/"
    email = "mailto:keswick@roundtable.org.uk"